-- Local-only compatible research tables. Skipped when APPLY_APP_STUBS=false
-- so an existing production-shaped database is not rewritten.

CREATE TABLE IF NOT EXISTS public.file (
    id INTEGER PRIMARY KEY,
    filename TEXT NOT NULL,
    description TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    private BOOLEAN NOT NULL DEFAULT FALSE,
    is_delete BOOLEAN NOT NULL DEFAULT FALSE,
    row_count INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.data_config (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id INTEGER NOT NULL REFERENCES public.file(id),
    field_key TEXT NOT NULL,
    label TEXT NOT NULL,
    config JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public.file_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id INTEGER NOT NULL REFERENCES public.file(id),
    version INTEGER NOT NULL,
    row_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.file_data_normalized (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_row_id BIGINT NOT NULL,
    file_id INTEGER NOT NULL REFERENCES public.file(id),
    version INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'ready',
    row_data_normalized JSONB NOT NULL DEFAULT '{}'::jsonb,
    search_text TEXT,
    canonical_name TEXT,
    canonical_community TEXT,
    canonical_school TEXT,
    source_created_at TIMESTAMPTZ,
    source_updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.communities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    variants TEXT[] NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS public.day_schools (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    variants TEXT[] NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS public.indian_hospitals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    variants TEXT[] NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS public.provinces (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT,
    variants TEXT[] NOT NULL DEFAULT '{}'
);

-- Forbidden operational tables exist locally only so privilege tests can fail closed.
CREATE TABLE IF NOT EXISTS public.users (
    id INTEGER PRIMARY KEY,
    email TEXT,
    password_hash TEXT
);
CREATE TABLE IF NOT EXISTS public.roles (
    id INTEGER PRIMARY KEY,
    name TEXT
);
CREATE TABLE IF NOT EXISTS public.otps (
    id INTEGER PRIMARY KEY,
    code TEXT
);
CREATE TABLE IF NOT EXISTS public.logs (
    id INTEGER PRIMARY KEY,
    body TEXT
);
CREATE TABLE IF NOT EXISTS public.support_requests (
    id INTEGER PRIMARY KEY,
    notes TEXT
);
CREATE TABLE IF NOT EXISTS public.file_access (
    id INTEGER PRIMARY KEY,
    user_id INTEGER,
    file_id INTEGER
);
CREATE TABLE IF NOT EXISTS public.file_edit_request (
    id INTEGER PRIMARY KEY,
    status TEXT
);
CREATE TABLE IF NOT EXISTS public.form_submissions (
    id INTEGER PRIMARY KEY,
    payload JSONB
);
