CREATE SCHEMA IF NOT EXISTS assistant;
CREATE SCHEMA IF NOT EXISTS assistant_api;

REVOKE ALL ON SCHEMA assistant FROM PUBLIC;
REVOKE ALL ON SCHEMA assistant_api FROM PUBLIC;

CREATE TABLE IF NOT EXISTS assistant.dataset_policy (
    file_id INTEGER PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    user_facing_label TEXT NOT NULL,
    is_default_people_scope BOOLEAN NOT NULL DEFAULT FALSE,
    history_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    attachment_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    private_policy_mode TEXT NOT NULL DEFAULT 'grant_required',
    configuration_version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS assistant.field_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id INTEGER NOT NULL,
    semantic_field TEXT NOT NULL,
    human_label TEXT NOT NULL,
    aliases TEXT[] NOT NULL DEFAULT '{}',
    canonical_json_path TEXT,
    raw_json_keys TEXT[] NOT NULL DEFAULT '{}',
    semantic_type TEXT NOT NULL,
    allowed_operators TEXT[] NOT NULL DEFAULT '{}',
    searchable BOOLEAN NOT NULL DEFAULT TRUE,
    aggregatable BOOLEAN NOT NULL DEFAULT FALSE,
    sortable BOOLEAN NOT NULL DEFAULT FALSE,
    quoteable BOOLEAN NOT NULL DEFAULT FALSE,
    sensitivity TEXT NOT NULL DEFAULT 'research',
    exposure_policy TEXT NOT NULL DEFAULT 'authorized',
    validation_rules JSONB NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (file_id, semantic_field)
);

CREATE TABLE IF NOT EXISTS assistant.access_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal_id TEXT NOT NULL,
    file_id INTEGER NOT NULL,
    grant_status TEXT NOT NULL DEFAULT 'active',
    expires_at TIMESTAMPTZ,
    source TEXT NOT NULL DEFAULT 'standalone',
    source_version TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (principal_id, file_id)
);

CREATE TABLE IF NOT EXISTS assistant.entity_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type TEXT NOT NULL,
    source_file_id INTEGER,
    source_row_id BIGINT,
    reference_key TEXT,
    canonical_display TEXT NOT NULL,
    alias TEXT NOT NULL,
    normalized_alias TEXT NOT NULL,
    phonetic_hint TEXT,
    tts_override TEXT,
    scope TEXT NOT NULL DEFAULT 'global',
    confidence REAL,
    verified BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS assistant.conversations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    principal_id TEXT NOT NULL,
    title TEXT,
    current_mode TEXT NOT NULL DEFAULT 'text',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS assistant.messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID NOT NULL REFERENCES assistant.conversations(id) ON DELETE CASCADE,
    turn_id TEXT NOT NULL,
    role TEXT NOT NULL,
    text TEXT,
    mode TEXT NOT NULL DEFAULT 'text',
    interrupted BOOLEAN NOT NULL DEFAULT FALSE,
    delivered_text_boundary INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS assistant.conversation_state (
    conversation_id UUID PRIMARY KEY REFERENCES assistant.conversations(id) ON DELETE CASCADE,
    rolling_summary TEXT,
    active_entities JSONB NOT NULL DEFAULT '{}'::jsonb,
    active_dataset_scope JSONB NOT NULL DEFAULT '{}'::jsonb,
    active_query_state JSONB NOT NULL DEFAULT '{}'::jsonb,
    last_source_ids TEXT[] NOT NULL DEFAULT '{}',
    pending_references JSONB NOT NULL DEFAULT '{}'::jsonb,
    state_version INTEGER NOT NULL DEFAULT 1,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS assistant.query_frames (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID NOT NULL REFERENCES assistant.conversations(id) ON DELETE CASCADE,
    frame_key TEXT NOT NULL,
    topic TEXT,
    entities JSONB NOT NULL DEFAULT '{}'::jsonb,
    logical_constraints JSONB NOT NULL DEFAULT '{}'::jsonb,
    result_set_ids UUID[] NOT NULL DEFAULT '{}',
    last_source_ids TEXT[] NOT NULL DEFAULT '{}',
    last_used_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (conversation_id, frame_key)
);

CREATE TABLE IF NOT EXISTS assistant.result_sets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID NOT NULL REFERENCES assistant.conversations(id) ON DELETE CASCADE,
    source_turn_id TEXT,
    record_type TEXT NOT NULL DEFAULT 'research_rows',
    file_ids INTEGER[] NOT NULL DEFAULT '{}',
    ordered_source_ids TEXT[] NOT NULL DEFAULT '{}',
    sort_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS assistant.query_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    turn_id TEXT NOT NULL,
    planner_type TEXT NOT NULL,
    plan_json JSONB NOT NULL,
    schema_version INTEGER NOT NULL DEFAULT 1,
    validation_status TEXT NOT NULL,
    plan_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS assistant.query_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    plan_id UUID REFERENCES assistant.query_plans(id) ON DELETE SET NULL,
    status TEXT NOT NULL,
    access_scope_fingerprint TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at TIMESTAMPTZ,
    latency_ms INTEGER,
    critical_path_ms INTEGER,
    parallel_step_peak INTEGER,
    queued_ms INTEGER,
    worker_id TEXT,
    instance_id TEXT,
    cancel_reason TEXT,
    error_category TEXT,
    result_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
    retry_count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS assistant.query_step_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    query_run_id UUID NOT NULL REFERENCES assistant.query_runs(id) ON DELETE CASCADE,
    step_id TEXT NOT NULL,
    operation TEXT NOT NULL,
    branch_group TEXT,
    ready_at TIMESTAMPTZ,
    queued_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    worker_id TEXT,
    attempt INTEGER NOT NULL DEFAULT 1,
    idempotency_key TEXT,
    timeout_ms INTEGER,
    cancelled BOOLEAN NOT NULL DEFAULT FALSE,
    result_count INTEGER,
    safe_result_ref TEXT,
    error_metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS assistant.citations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    message_id UUID REFERENCES assistant.messages(id) ON DELETE CASCADE,
    turn_id TEXT NOT NULL,
    claim_id TEXT,
    file_id INTEGER NOT NULL,
    version INTEGER NOT NULL,
    source_row_id BIGINT NOT NULL,
    field_path TEXT,
    attachment_chunk_id UUID,
    citation_label TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS assistant.voice_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID REFERENCES assistant.conversations(id) ON DELETE CASCADE,
    livekit_room TEXT,
    livekit_identity TEXT,
    generation_id TEXT,
    tts_stream_id TEXT,
    xai_tts_connection_state TEXT,
    xai_tts_connected_at TIMESTAMPTZ,
    first_audio_latency_ms INTEGER,
    barge_in_cancel_latency_ms INTEGER,
    interrupted_at TIMESTAMPTZ,
    reconnected_at TIMESTAMPTZ,
    final_state TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS assistant.feedback (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID REFERENCES assistant.conversations(id) ON DELETE CASCADE,
    turn_id TEXT,
    message_id UUID REFERENCES assistant.messages(id) ON DELETE SET NULL,
    rating TEXT,
    category TEXT,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS assistant.audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal_id TEXT,
    event_type TEXT NOT NULL,
    conversation_id UUID,
    query_run_id UUID,
    dataset_ids INTEGER[] NOT NULL DEFAULT '{}',
    authorization_outcome TEXT,
    provider_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS assistant.background_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_type TEXT NOT NULL,
    target_dataset_id INTEGER,
    resource_class TEXT,
    priority INTEGER NOT NULL DEFAULT 100,
    state TEXT NOT NULL DEFAULT 'queued',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    idempotency_key TEXT,
    worker_id TEXT,
    next_retry_at TIMESTAMPTZ,
    lease_expires_at TIMESTAMPTZ,
    heartbeat_at TIMESTAMPTZ,
    error_summary TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS assistant.attachment_sources (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_attachment_id TEXT,
    file_id INTEGER NOT NULL,
    source_row_id BIGINT,
    approved_url TEXT,
    media_type TEXT,
    checksum TEXT,
    fetch_status TEXT NOT NULL DEFAULT 'pending',
    source_metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS assistant.attachment_chunks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    attachment_source_id UUID NOT NULL REFERENCES assistant.attachment_sources(id) ON DELETE CASCADE,
    page_number INTEGER,
    section TEXT,
    chunk_number INTEGER NOT NULL,
    extracted_text TEXT,
    search_vector tsvector,
    provenance JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS assistant.schema_migrations (
    filename TEXT PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_field_registry_file ON assistant.field_registry (file_id);
CREATE INDEX IF NOT EXISTS idx_access_grants_principal ON assistant.access_grants (principal_id);
CREATE INDEX IF NOT EXISTS idx_conversations_principal ON assistant.conversations (principal_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON assistant.messages (conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_query_frames_last_used ON assistant.query_frames (conversation_id, last_used_at DESC);
CREATE INDEX IF NOT EXISTS idx_result_sets_expiry ON assistant.result_sets (expires_at);
CREATE INDEX IF NOT EXISTS idx_query_runs_started ON assistant.query_runs (started_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_created ON assistant.audit_events (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_jobs_state ON assistant.background_jobs (state, priority, created_at);
